Added badges to match flip-remote project
arshadkazmi42/strmat pull request #7
Opened 2019-05-28 23:29 UTC by paigeribera

Added all the badges that were on the flip-remote project. Issue #5

2019-05-29 04:49 UTC, arshadkazmi42 requested changes
Looks good.
We don't want to delete package.json file.
Can you add that file back.

2019-05-30 01:25 UTC, paigeribera commented
Okay! Sorry about that. I think I've fixed it now.

2019-05-30 03:00 UTC, arshadkazmi42 requested changes
There is a minor change and it will be good to go.

2019-05-30 03:00 UTC, arshadkazmi42 commented on package.json
> +  "dependencies": {
This does not belongs here.
Can you remove the dependencies.
It does not uses any dependencies and same package we cannot use as dependency.
So complete depencies object should be removed

2019-06-01 16:22 UTC, paigeribera commented
okay, I've gotten rid of those dependencies.

2019-06-01 17:29 UTC, arshadkazmi42 approved these changes
Awesome 💯

2019-06-01 17:29 UTC, merged